// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownloadJob = `-- name: CreateDownloadJob :one
INSERT INTO devon_download_jobs (model_id, bonnie_agent_id, status, patterns)
VALUES ($1, $2, 'pending', $3)
RETURNING id, model_id, bonnie_agent_id, status, patterns, error, started_at, finished_at, created_at, updated_at
`

type CreateDownloadJobParams struct {
	ModelID       pgtype.UUID `json:"model_id"`
	BonnieAgentID pgtype.UUID `json:"bonnie_agent_id"`
	Patterns      []byte      `json:"patterns"`
}

func (q *Queries) CreateDownloadJob(ctx context.Context, arg CreateDownloadJobParams) (DevonDownloadJob, error) {
	row := q.db.QueryRow(ctx, createDownloadJob, arg.ModelID, arg.BonnieAgentID, arg.Patterns)
	var i DevonDownloadJob
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.BonnieAgentID,
		&i.Status,
		&i.Patterns,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadJob = `-- name: GetDownloadJob :one
SELECT id, model_id, bonnie_agent_id, status, patterns, error, started_at, finished_at, created_at, updated_at FROM devon_download_jobs WHERE id = $1
`

func (q *Queries) GetDownloadJob(ctx context.Context, id pgtype.UUID) (DevonDownloadJob, error) {
	row := q.db.QueryRow(ctx, getDownloadJob, id)
	var i DevonDownloadJob
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.BonnieAgentID,
		&i.Status,
		&i.Patterns,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDownloadJobs = `-- name: ListDownloadJobs :many
SELECT id, model_id, bonnie_agent_id, status, patterns, error, started_at, finished_at, created_at, updated_at FROM devon_download_jobs ORDER BY created_at DESC
`

func (q *Queries) ListDownloadJobs(ctx context.Context) ([]DevonDownloadJob, error) {
	rows, err := q.db.Query(ctx, listDownloadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevonDownloadJob{}
	for rows.Next() {
		var i DevonDownloadJob
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.BonnieAgentID,
			&i.Status,
			&i.Patterns,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDownloadJobs = `-- name: ListPendingDownloadJobs :many
SELECT id, model_id, bonnie_agent_id, status, patterns, error, started_at, finished_at, created_at, updated_at FROM devon_download_jobs WHERE status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingDownloadJobs(ctx context.Context) ([]DevonDownloadJob, error) {
	rows, err := q.db.Query(ctx, listPendingDownloadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevonDownloadJob{}
	for rows.Next() {
		var i DevonDownloadJob
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.BonnieAgentID,
			&i.Status,
			&i.Patterns,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDownloadJobFailed = `-- name: MarkDownloadJobFailed :exec
UPDATE devon_download_jobs
SET status = 'failed', finished_at = now(), updated_at = now(), error = $2
WHERE id = $1
`

type MarkDownloadJobFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error string      `json:"error"`
}

func (q *Queries) MarkDownloadJobFailed(ctx context.Context, arg MarkDownloadJobFailedParams) error {
	_, err := q.db.Exec(ctx, markDownloadJobFailed, arg.ID, arg.Error)
	return err
}

const markDownloadJobRunning = `-- name: MarkDownloadJobRunning :exec
UPDATE devon_download_jobs
SET status = 'running', started_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDownloadJobRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDownloadJobRunning, id)
	return err
}

const markDownloadJobSucceeded = `-- name: MarkDownloadJobSucceeded :exec
UPDATE devon_download_jobs
SET status = 'succeeded', finished_at = now(), updated_at = now(), error = ''
WHERE id = $1
`

func (q *Queries) MarkDownloadJobSucceeded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDownloadJobSucceeded, id)
	return err
}

const restartDownloadJob = `-- name: RestartDownloadJob :exec
UPDATE devon_download_jobs
SET status = 'pending', started_at = NULL, finished_at = NULL, error = '', updated_at = now()
WHERE id = $1
`

func (q *Queries) RestartDownloadJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restartDownloadJob, id)
	return err
}
