// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DevonBonnieAgent struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Token      string             `json:"token"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DevonDownloadJob struct {
	ID            pgtype.UUID        `json:"id"`
	ModelID       pgtype.UUID        `json:"model_id"`
	BonnieAgentID pgtype.UUID        `json:"bonnie_agent_id"`
	Status        string             `json:"status"`
	Patterns      []byte             `json:"patterns"`
	Error         string             `json:"error"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DevonModel struct {
	ID           pgtype.UUID        `json:"id"`
	Source       string             `json:"source"`
	ModelID      string             `json:"model_id"`
	Metadata     []byte             `json:"metadata"`
	DownloadedAt pgtype.Timestamptz `json:"downloaded_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DevonPlacement struct {
	ID            pgtype.UUID        `json:"id"`
	ModelID       pgtype.UUID        `json:"model_id"`
	BonnieAgentID pgtype.UUID        `json:"bonnie_agent_id"`
	RemoteEntryID string             `json:"remote_entry_id"`
	HostPath      string             `json:"host_path"`
	SizeBytes     int64              `json:"size_bytes"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}
