// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM devon_models WHERE id = $1
`

func (q *Queries) DeleteModel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteModel, id)
	return err
}

const getModel = `-- name: GetModel :one
SELECT id, source, model_id, metadata, downloaded_at, last_used_at, created_at, updated_at FROM devon_models WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id pgtype.UUID) (DevonModel, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i DevonModel
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ModelID,
		&i.Metadata,
		&i.DownloadedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelByIdentity = `-- name: GetModelByIdentity :one
SELECT id, source, model_id, metadata, downloaded_at, last_used_at, created_at, updated_at FROM devon_models WHERE source = $1 AND model_id = $2
`

type GetModelByIdentityParams struct {
	Source  string `json:"source"`
	ModelID string `json:"model_id"`
}

func (q *Queries) GetModelByIdentity(ctx context.Context, arg GetModelByIdentityParams) (DevonModel, error) {
	row := q.db.QueryRow(ctx, getModelByIdentity, arg.Source, arg.ModelID)
	var i DevonModel
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ModelID,
		&i.Metadata,
		&i.DownloadedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, source, model_id, metadata, downloaded_at, last_used_at, created_at, updated_at FROM devon_models ORDER BY source, model_id
`

func (q *Queries) ListModels(ctx context.Context) ([]DevonModel, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevonModel{}
	for rows.Next() {
		var i DevonModel
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ModelID,
			&i.Metadata,
			&i.DownloadedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelDownloaded = `-- name: MarkModelDownloaded :exec
UPDATE devon_models
SET downloaded_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkModelDownloaded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markModelDownloaded, id)
	return err
}

const touchModelUsed = `-- name: TouchModelUsed :exec
UPDATE devon_models
SET last_used_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchModelUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchModelUsed, id)
	return err
}

const upsertModel = `-- name: UpsertModel :one
INSERT INTO devon_models (source, model_id, metadata)
VALUES ($1, $2, $3)
ON CONFLICT (source, model_id) DO UPDATE
    SET metadata = EXCLUDED.metadata,
        updated_at = now()
RETURNING id, source, model_id, metadata, downloaded_at, last_used_at, created_at, updated_at
`

type UpsertModelParams struct {
	Source   string `json:"source"`
	ModelID  string `json:"model_id"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) (DevonModel, error) {
	row := q.db.QueryRow(ctx, upsertModel, arg.Source, arg.ModelID, arg.Metadata)
	var i DevonModel
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ModelID,
		&i.Metadata,
		&i.DownloadedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
