// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlacement = `-- name: DeletePlacement :exec
DELETE FROM devon_placements WHERE id = $1
`

func (q *Queries) DeletePlacement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlacement, id)
	return err
}

const deletePlacementsByModel = `-- name: DeletePlacementsByModel :exec
DELETE FROM devon_placements WHERE model_id = $1
`

func (q *Queries) DeletePlacementsByModel(ctx context.Context, modelID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlacementsByModel, modelID)
	return err
}

const getPlacement = `-- name: GetPlacement :one
SELECT id, model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes, fetched_at FROM devon_placements WHERE id = $1
`

func (q *Queries) GetPlacement(ctx context.Context, id pgtype.UUID) (DevonPlacement, error) {
	row := q.db.QueryRow(ctx, getPlacement, id)
	var i DevonPlacement
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.BonnieAgentID,
		&i.RemoteEntryID,
		&i.HostPath,
		&i.SizeBytes,
		&i.FetchedAt,
	)
	return i, err
}

const getPlacementByModelAgent = `-- name: GetPlacementByModelAgent :one
SELECT id, model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes, fetched_at FROM devon_placements WHERE model_id = $1 AND bonnie_agent_id = $2
`

type GetPlacementByModelAgentParams struct {
	ModelID       pgtype.UUID `json:"model_id"`
	BonnieAgentID pgtype.UUID `json:"bonnie_agent_id"`
}

func (q *Queries) GetPlacementByModelAgent(ctx context.Context, arg GetPlacementByModelAgentParams) (DevonPlacement, error) {
	row := q.db.QueryRow(ctx, getPlacementByModelAgent, arg.ModelID, arg.BonnieAgentID)
	var i DevonPlacement
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.BonnieAgentID,
		&i.RemoteEntryID,
		&i.HostPath,
		&i.SizeBytes,
		&i.FetchedAt,
	)
	return i, err
}

const listPlacements = `-- name: ListPlacements :many
SELECT id, model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes, fetched_at FROM devon_placements ORDER BY fetched_at DESC
`

func (q *Queries) ListPlacements(ctx context.Context) ([]DevonPlacement, error) {
	rows, err := q.db.Query(ctx, listPlacements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevonPlacement{}
	for rows.Next() {
		var i DevonPlacement
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.BonnieAgentID,
			&i.RemoteEntryID,
			&i.HostPath,
			&i.SizeBytes,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacementsByAgent = `-- name: ListPlacementsByAgent :many
SELECT id, model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes, fetched_at FROM devon_placements WHERE bonnie_agent_id = $1 ORDER BY fetched_at DESC
`

func (q *Queries) ListPlacementsByAgent(ctx context.Context, bonnieAgentID pgtype.UUID) ([]DevonPlacement, error) {
	rows, err := q.db.Query(ctx, listPlacementsByAgent, bonnieAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevonPlacement{}
	for rows.Next() {
		var i DevonPlacement
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.BonnieAgentID,
			&i.RemoteEntryID,
			&i.HostPath,
			&i.SizeBytes,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacementsByModel = `-- name: ListPlacementsByModel :many
SELECT id, model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes, fetched_at FROM devon_placements WHERE model_id = $1 ORDER BY fetched_at DESC
`

func (q *Queries) ListPlacementsByModel(ctx context.Context, modelID pgtype.UUID) ([]DevonPlacement, error) {
	rows, err := q.db.Query(ctx, listPlacementsByModel, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DevonPlacement{}
	for rows.Next() {
		var i DevonPlacement
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.BonnieAgentID,
			&i.RemoteEntryID,
			&i.HostPath,
			&i.SizeBytes,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlacement = `-- name: UpsertPlacement :one
INSERT INTO devon_placements (model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (model_id, bonnie_agent_id) DO UPDATE
    SET remote_entry_id = EXCLUDED.remote_entry_id,
        host_path       = EXCLUDED.host_path,
        size_bytes      = EXCLUDED.size_bytes,
        fetched_at      = now()
RETURNING id, model_id, bonnie_agent_id, remote_entry_id, host_path, size_bytes, fetched_at
`

type UpsertPlacementParams struct {
	ModelID       pgtype.UUID `json:"model_id"`
	BonnieAgentID pgtype.UUID `json:"bonnie_agent_id"`
	RemoteEntryID string      `json:"remote_entry_id"`
	HostPath      string      `json:"host_path"`
	SizeBytes     int64       `json:"size_bytes"`
}

func (q *Queries) UpsertPlacement(ctx context.Context, arg UpsertPlacementParams) (DevonPlacement, error) {
	row := q.db.QueryRow(ctx, upsertPlacement,
		arg.ModelID,
		arg.BonnieAgentID,
		arg.RemoteEntryID,
		arg.HostPath,
		arg.SizeBytes,
	)
	var i DevonPlacement
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.BonnieAgentID,
		&i.RemoteEntryID,
		&i.HostPath,
		&i.SizeBytes,
		&i.FetchedAt,
	)
	return i, err
}
